
# NOTE: Didn't use docker-compose, instead set up the network and docker files using the following txt instructions:
# 1: setup-docker-network.txt
# 2: backend-stormrider-docker-instructions.txt
# 3: docker-frontend-instructions-stormrider.txt

version: "3"
services:
  stormrider-backend:
    container_name: stormrider-backend
    restart: always
    build:
      ./storm-backend
    ports:
    - "8888:8888"
  stormrider-frontend:
    container_name: stormrider-frontend
    restart: always
    build:
      ./storm-frontend
    ports:
    - "3000:3000"
    links:
      - stormrider-backend
